name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy-upm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://upm.fenrirserver.org/

      - run: npm publish
        working-directory: UnityPackage/Assets
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
